### ISSUE TITLE
Web tutorial missing npm install

### ISSUE THREAD

**Issue by jenessawhite** [spotify/web-api-auth-examples#12]
On your [Web-API Tutorial](https://developer.spotify.com/web-api/tutorial/) you require the 'cookie-parser' node package, however you don't state it where you are telling users what npm's to install in the "Creating the Project Folder and Files" section.

**Comment by JMPerez** [comment]
@jenessawhite If you run `npm install`from your cloned repo you will download several dependencies, included `cookie-parser`, which is listed in the [package.json](https://github.com/spotify/web-api-auth-examples/blob/master/package.json#L7).

**Comment by jenessawhite** [comment]
It was doing some weird things when I just ran `npm install` so i just manually did the `npm install cookie-parser` and it worked. Thanks!

**Comment by JMPerez** [comment]
@jenessawhite No problem!

**Comment by LivroD** [comment]
Hi I seem to have the same problem as the person above and despite using the workaround I still seem to be getting errors https://i.imgur.com/VK7faWF.png. Could you please help
