### ISSUE TITLE
Invalid redirect URI

### ISSUE THREAD

**Issue by craig-doyle-uk** [spotify/web-api-auth-examples#25]
I have set my redirect URI do be `http://localhost:8888/callback/` in the Spotify dashboard for my app and set the `redirect_uri` variable to `http://localhost:8888/callback` in the example, but as soon as I visit `http://localhost:8888/login` an empty browser window is displayed with the following message : `INVALID_CLIENT: Invalid redirect URI` and the url in the address bar is as follows : https://accounts.spotify.com/authorize?response_type=code&client_id=40e1d1267f2d447189fdc004f7d5aa1e&scope=user-read-email&redirect_uri=http%3A%2F%2Flocalhost%3A8888%2Fcallback&state=IlvEOLr81HceC2TB

Am I doing anything wrong, or are these examples no longer valid?

Thanks in advance for any advice you can give!

**Comment by craig-doyle-uk** [comment]
This has started working this evening- no idea why it wasn't earlier.

**Comment by EmDmx** [comment]
I am having the exact problem right now and couldn't find any solutions for it.

**Comment by cathyleeu** [comment]
Anyone who find any solutions about it? im stuck in it...

**Comment by omadume** [comment]
me too, it was working then just stopped.

**Comment by guptaabhijit** [comment]
Maybe because of browsers cookies. Open in incognito mode. It worked for me. Don't forget to add redirect uri on dashboard

**Comment by keeravani** [comment]
you'd have to whitelist the redirect uri in the spotify dashboard
