### ISSUE TITLE
Simple auth. example always return INVALID_CLIENT: Invalid redirect URI

### ISSUE THREAD

**Issue by lonnibesancon** [spotify/web-api-auth-examples#26]
I tried your simple auth. example and it always return INVALID_CLIENT: Invalid redirect URI in my browser, even though I did use the client ID given in my app (with the good secret) and set the redirect URI to "http://localhost:8888" as suggested here: https://beta.developer.spotify.com/documentation/web-api/quick-start/

Would you know what the problem is?

**Comment by arirawr** [comment]
Hi @lonnibesancon - you need to go into your [dashboard on Spotify for Developers](https://beta.developer.spotify.com/dashboard/), select your app, and add the redirect URI to your app by clicking on "Edit Settings".

**Comment by arirawr** [comment]
It's covered in the section called "Register Your App", which links [here](https://beta.developer.spotify.com/documentation/general/guides/app-settings/#register-your-app). I agree it could be way clearer - I'll look into changing that!

**Comment by rodasmed** [comment]
@arirawr I added the redirect URI to my app & it.s still not working

**Comment by HienH** [comment]
Hi, make sure you click the save button on the bottom as well as the add button, then it should work :)

**Comment by isaacdecuba** [comment]
@arirawr make sure that the redirect_uri ends with a `/`

**Comment by bgp09002** [comment]
> @arirawr make sure that the redirect_uri ends with a `/`

@isaacdecuba  Hi I've followed all of these steps listed and i'm still getting the  Illegal redirect_uri  browser popup 

I have `http://localhost:8888/` listed in my code and submitted to the redirect URIs on my app. Any other recommendations?

**Comment by lishap** [comment]
Having the same issue. Using "http://localhost/final-lookback/index.html/" on a XXAMP server off of Mac.

**Comment by kukovisuals** [comment]
on developer.spotify redirect uri = http://localhost/callback/  
on app.js  =  var redirect_uri = 'http://localhost:8888/'; // Your redirect uri

**Comment by zhangium** [comment]
I was running into this issue as well and this is what worked for me.

On developer.spotify I added the uri:
http://localhost:8888/

In app.js:
`var redirect_uri = 'http://localhost:8888/callback/';`

**Comment by thomasmallick** [comment]
@bgp09002 try making the app.js redirect_URI: 
var redirect_uri = 'http://localhost:8888/callback'; (as the tutorial specifies)
and ensuring that the app dashboard's saved Redirect URI's includes that exact same URI (i.e. http://localhost:8888/**callback**)

**Comment by martin11cortes** [comment]
If its useful to someone:
I had to change the **app.js** `redirect_uri` to `http://localhost.com:8888/callback/` and copy exactly the same into the **Spotify App** `Redirect URIs`

**Comment by duck-stack** [comment]
I found that the only way to get it to work, is to set your redirect uri as something with a unique prefix, NOT "http" or "https" and include a "/" at the very end.

so instead of "http://localhost:8888", try "my://app/." 

Be sure to update it in your dashboard, save it, and update it in your code as well. When you run it, it will take you a page where you log into your spotify account

**Comment by usmankh03777** [comment]
I have spotted the best solution. Just use like https://localhost:3000/ And boom the problem is solved totally.

**Comment by Kumar2106** [comment]
i have tried making the the redirect uri in the react app and in the dashboard same, but it is still giving me the same error, do anyone know how to resolve it.

**Comment by AndyVac87** [comment]
Make sure you have no spaces where you have your redirect_uri, in your program code and/or the Spotify for developer settings. I hope it helped.
