### ISSUE TITLE
INVALID_CLIENT: Invalid redirect URI

### ISSUE THREAD

**Issue by igorlopez** [spotify/web-api-auth-examples#28]
Hi,

This is probably a very stupid issue but I have fetched the code, updated app.js client_id, client_secret and redirect_uri

```java
var client_id = 'my client id'; // Your client id
var client_secret = 'my secret'; // Your secret
var redirect_uri = 'http://localhost:8888/callback'; // Your redirect uri
```

Starting the app in the folder where app.js is located:

```
:~/Development/Spotify/web-api-auth-examples/authorization_code$ nodejs app.js
Listening on 8888
```
(Note that it is not node since I am running Ubuntu and there it is nodejs.)
![startpage](https://user-images.githubusercontent.com/109189/46916299-dc320d80-cfb8-11e8-93eb-e5db88e674f6.png)

When pressing the "Log in with Spotify" button I get this:
![ivalid_client_issue](https://user-images.githubusercontent.com/109189/46916328-316e1f00-cfb9-11e8-96b2-3bc155693386.png)

I have made a wireshark log during the transaction but can't make anything out of it.

In another issue was the question raised to test that the server is listening to that redirect_uri which here comes up as:
![state_mismatch](https://user-images.githubusercontent.com/109189/46916383-10f29480-cfba-11e8-9185-58e8e0d9477a.png)

and running curl:
:~$ curl http://localhost:8888/callback
Found. Redirecting to /#error=state_mismatch

Any ideas?

**Comment by igorlopez** [comment]
The issue was to read here instead on a webpage.
I had missed these instructions:

> To do so, go to your Spotify for Developers Dashboard and create your application. For the examples, we registered these Redirect URIs:

    http://localhost:8888 (needed for the implicit grant flow)
    http://localhost:8888/callback

Now it works as expected

**Comment by aslam500** [comment]
it happen to me also ,solution is instead of giving http://localhost:3000 as redirect uri give http://192.168.42.130:3000,which is obtained at the terminal after running npm start.
