### ISSUE TITLE
CORS not working here

### ISSUE THREAD

**Issue by gregorkleiber** [spotify/web-api-auth-examples#37]
Server gets user information.
Client request gets rejected: "Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.spotify.com/v1/me. (Reason: CORS request did not succeed)."

I don't know how to fix this.

BR

**Comment by Casey6624** [comment]
Try enabling this during development

https://chrome.google.com/webstore/detail/allow-cors-access-control/lhobafahddgcelffkeicbaginigeejlf?hl=en

**Comment by Colnup** [comment]
I've got the same issue. I tried to install https://addons.mozilla.org/en-US/firefox/addon/access-control-allow-origin/ and enabled it, it worked on the test webpage (https://webbrowsertools.com/test-cors/), but still don't work on localhost:8888/ , and I get the same "Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.spotify.com/v1/me. (Reason: CORS request did not succeed)." than Gregor.

I don't know how to fix, please help.
