### ISSUE TITLE
Issue with new spotify endpoint?

### ISSUE THREAD

**Issue by FrenchBully** [spotify/web-api-auth-examples#8]
I'm not sure if I'm doing something wrong, but for some reason when I pass in the new scope 'user-top-read', I get a token that doesn't allow me to hit this endpoint.  There are no errors, nor does it return anything.  Any thoughts?  Thanks

[https://api.spotify.com/v1/me/top/{type}](https://developer.spotify.com/web-api/console/get-current-user-top-artists-and-tracks/)

Never mind, looks like it's fixed now.

**Comment by JMPerez** [comment]
@FrenchBully I am closing this ticket since it seems to be fixed.
