### ISSUE TITLE
Buffer depreciated

### ISSUE THREAD

**Issue by Yasar195** [spotify/web-api-auth-examples#91]
### Buffer deprecated
i've noticed there is a depreciated warning from the use Buffer class from **Authorization** example

**Comment by ddoggdiggitty** [comment]
I would suggest replacing [line 19](https://github.com/spotify/web-api-auth-examples/blob/0bc3806a6bd63c538f26b0a9906df4fae67c545d/client_credentials/app.js#L19)  of the app.js file with the following code

```javascript
'Authorization' : 'Basic ' + (new Buffer.from(client_id + ':' + client_secret, 'toBase64'))
```
Perhaps that might work?

**Comment by Yasar195** [comment]
Thanks mate that's worked for me
